/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package diasemana;

import javax.swing.JOptionPane;

/**
 *
 * @author CBN
 */
public class FrmDiaSemana extends javax.swing.JFrame {

    /**
     * Creates new form FrmDiaSemana
     */
    public FrmDiaSemana() {
        initComponents();
        lbRespuesta.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgDiaSemana = new javax.swing.ButtonGroup();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMiercoles = new javax.swing.JRadioButton();
        rbJueves = new javax.swing.JRadioButton();
        rbViernes = new javax.swing.JRadioButton();
        rbSabado = new javax.swing.JRadioButton();
        rbDomingo = new javax.swing.JRadioButton();
        lbRespuesta = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rgDiaSemana.add(rbLunes);
        rbLunes.setText("Lunes");
        rbLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunesActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbMartes);
        rbMartes.setText("Martes");
        rbMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMartesActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbMiercoles);
        rbMiercoles.setText("Miercoles");
        rbMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMiercolesActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbJueves);
        rbJueves.setText("Jueves");
        rbJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbJuevesActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbViernes);
        rbViernes.setText("Viernes");
        rbViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViernesActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbSabado);
        rbSabado.setText("Sabado");
        rbSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSabadoActionPerformed(evt);
            }
        });

        rgDiaSemana.add(rbDomingo);
        rbDomingo.setText("Domingo");
        rbDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDomingoActionPerformed(evt);
            }
        });

        lbRespuesta.setText("jLabel1");

        btnReset.setText("Reseteame <3");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLunes)
                    .addComponent(rbMartes)
                    .addComponent(rbMiercoles)
                    .addComponent(rbJueves)
                    .addComponent(rbViernes)
                    .addComponent(rbSabado)
                    .addComponent(rbDomingo)
                    .addComponent(lbRespuesta)
                    .addComponent(btnReset))
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbLunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMartes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMiercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbJueves)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbViernes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDomingo)
                .addGap(18, 18, 18)
                .addComponent(lbRespuesta)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunesActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
        
    }//GEN-LAST:event_rbLunesActionPerformed

    private void rbMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMartesActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbMartesActionPerformed

    private void rbMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMiercolesActionPerformed
        // TODO add your handling code here:
       lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbMiercolesActionPerformed

    private void rbJuevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbJuevesActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbJuevesActionPerformed

    private void rbViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViernesActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbViernesActionPerformed

    private void rbSabadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSabadoActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbSabadoActionPerformed

    private void rbDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDomingoActionPerformed
        // TODO add your handling code here:
        lbRespuesta.setText(GenerarMensaje());
    }//GEN-LAST:event_rbDomingoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       rgDiaSemana.clearSelection();
        lbRespuesta.setText("");
        JOptionPane.showMessageDialog(rootPane, "Ya me Reseteaste");
    }//GEN-LAST:event_btnResetActionPerformed

    private String GenerarMensaje(){
        String respuesta = "";
        if (rbLunes.isSelected()) {
            respuesta = "has seleccionado Lunes";
        }else if(rbMartes.isSelected()){
             respuesta = "has seleccionado Martes";
        }else if(rbMiercoles.isSelected()){
             respuesta = "has seleccionado Miercoles";
        }else if(rbJueves.isSelected()){
             respuesta = "has seleccionado Jueves";
        }else if(rbViernes.isSelected()){
             respuesta = "has seleccionado Viernes";
        }else if(rbSabado.isSelected()){
             respuesta = "has seleccionado Sabado";
        }else{
             respuesta = "has seleccionado Domingo";
        }
        return respuesta;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiaSemana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiaSemana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lbRespuesta;
    private javax.swing.JRadioButton rbDomingo;
    private javax.swing.JRadioButton rbJueves;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMiercoles;
    private javax.swing.JRadioButton rbSabado;
    private javax.swing.JRadioButton rbViernes;
    private javax.swing.ButtonGroup rgDiaSemana;
    // End of variables declaration//GEN-END:variables
}
